version: "3.8"

services:
  app:
    image: echo-sample
    platform: linux/amd64
    build:
      context: .
      dockerfile: Dockerfile
      no_cache: true
    ports:
      - "1324:1324"
      - "40010:40010"  # delveデバッグポート
    volumes:
      - ./main:/main        # ソースコードをマウント
    env_file:
      - main/.env
    depends_on:
      db:
        condition: service_healthy
    networks:
      - echo-network

  db:
    image: mysql:8.0
    container_name: sakila_mysql
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    volumes:
      - ./docker/mysql/sql:/docker-entrypoint-initdb.d
      - mysql_data:/var/lib/mysql
      - ./docker/mysql/mysql-logs:/var/log/mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: sakila
      MYSQL_ROOT_PASSWORD: password
      MYSQL_USER: user
      MYSQL_PASSWORD: passw0rd
      TZ: "Asia/Tokyo"
    networks:
      - echo-network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-ppassword"]
      timeout: 20s
      retries: 10
      interval: 10s
      start_period: 30s
    restart: unless-stopped

volumes:
  mysql_data:

networks:
  echo-network:
    driver: bridge 