// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package di

import (
	"echoProject/main/app/controller/city"
	"echoProject/main/domain/controller"
	"echoProject/main/infra/datasource/city"
	city2 "echoProject/main/infra/repository/city"
	"echoProject/main/infra/things/sqlboiler"
	city3 "echoProject/main/usecase/city"
	"github.com/google/wire"
)

// Injectors from wire.go:

func InitializeController() (*ControllersSet, error) {
	sqlBoiler := sqlboiler.NewSQLBoilerImpl()
	datasourceCity := city.NewCityDataSource(sqlBoiler)
	repositoryCity := city2.NewCityRepository(datasourceCity)
	usecaseCity := city3.NewCityService(repositoryCity)
	controllerCity := ctrcity.NewCityController(usecaseCity)
	controllersSet := &ControllersSet{
		CityController: controllerCity,
	}
	return controllersSet, nil
}

func InitializeDB() (*initializeDBSet, error) {
	sqlBoiler := sqlboiler.NewSQLBoilerImpl()
	diInitializeDBSet := &initializeDBSet{
		SqlBoiler: sqlBoiler,
	}
	return diInitializeDBSet, nil
}

// wire.go:

var infrastructureSet = wire.NewSet(city.NewCityDataSource, sqlboiler.NewSQLBoilerImpl)

var repositorySet = wire.NewSet(city2.NewCityRepository)

var usecaseSet = wire.NewSet(city3.NewCityService)

var controllerSet = wire.NewSet(ctrcity.NewCityController)

type ControllersSet struct {
	CityController controller.City
}

type initializeDBSet struct {
	SqlBoiler sqlboiler.SQLBoiler
}
