// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package di

import (
	city4 "echoProject/main/app/controller/city"
	country4 "echoProject/main/app/controller/country"
	"echoProject/main/domain/controller"
	"echoProject/main/infra/datasource/city"
	"echoProject/main/infra/datasource/country"
	city2 "echoProject/main/infra/repository/city"
	country2 "echoProject/main/infra/repository/country"
	"echoProject/main/infra/things/sqlboiler"
	city3 "echoProject/main/usecase/city"
	country3 "echoProject/main/usecase/country"
	"github.com/google/wire"
)

// Injectors from wire.go:

func InitializeController() (*ControllersSet, error) {
	sqlBoiler := sqlboiler.NewSQLBoilerImpl()
	datasourceCity := city.NewCityDataSource(sqlBoiler)
	repositoryCity := city2.NewCityRepository(datasourceCity)
	usecaseCity := city3.NewCityService(repositoryCity)
	controllerCity := city4.NewCityController(usecaseCity)
	datasourceCountry := country.NewCountryDataSource(sqlBoiler)
	repositoryCountry := country2.NewCountryRepository(datasourceCountry)
	usecaseCountry := country3.NewCountryService(repositoryCountry)
	controllerCountry := country4.NewCountryController(usecaseCountry)
	controllersSet := &ControllersSet{
		CityController:    controllerCity,
		CountryController: controllerCountry,
	}
	return controllersSet, nil
}

func InitializeDB() (*initializeDBSet, error) {
	sqlBoiler := sqlboiler.NewSQLBoilerImpl()
	diInitializeDBSet := &initializeDBSet{
		SqlBoiler: sqlBoiler,
	}
	return diInitializeDBSet, nil
}

// wire.go:

var infrastructureSet = wire.NewSet(city.NewCityDataSource, country.NewCountryDataSource, sqlboiler.NewSQLBoilerImpl)

var repositorySet = wire.NewSet(city2.NewCityRepository, country2.NewCountryRepository)

var usecaseSet = wire.NewSet(city3.NewCityService, country3.NewCountryService)

var controllerSet = wire.NewSet(city4.NewCityController, country4.NewCountryController)

type ControllersSet struct {
	CityController    controller.City
	CountryController controller.Country
}

type initializeDBSet struct {
	SqlBoiler sqlboiler.SQLBoiler
}
