version: "3.6"
services:
  db:
    image: mysql:8.0
    container_name: sakila_mysql
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    volumes:
      - ./sql:/docker-entrypoint-initdb.d
      - ./mysql-logs:/var/log/mysql
    ports:
      - 3306:3306
    environment:
      MYSQL_DATABASE: sakila
      MYSQL_ROOT_PASSWORD: password
      MYSQL_USER: user
      MYSQL_PASSWORD: passw0rd
      TZ: "Asia/Tokyo"