basePath: /
definitions:
  entity.City:
    properties:
      city:
        type: string
      city_id:
        type: integer
      country_id:
        type: integer
      last_update:
        type: string
    type: object
  entity.Country:
    properties:
      country:
        type: string
      countryID:
        format: int32
        type: integer
      lastUpdate:
        type: string
    type: object
host: localhost:1324
info:
  contact:
    email: support@swagger.io
    name: API Support
    url: http://www.swagger.io/support
  description: This is a sample Echo server with Sakila database.
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  termsOfService: http://swagger.io/terms/
  title: Echo Sample Project API
  version: "1.0"
paths:
  /cities:
    get:
      consumes:
      - application/json
      description: Retrieve all cities from the database
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/entity.City'
            type: array
      summary: Get all cities
      tags:
      - cities
  /countries:
    get:
      consumes:
      - application/json
      description: Retrieve all countries from the database
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/entity.Country'
            type: array
      summary: Get all countries
      tags:
      - countries
    post:
      consumes:
      - application/json
      description: Add a new country to the database
      parameters:
      - description: Country object
        in: body
        name: country
        required: true
        schema:
          type: object
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            additionalProperties: true
            type: object
        "400":
          description: Bad Request
          schema:
            additionalProperties: true
            type: object
      summary: Create a new country
      tags:
      - countries
  /health:
    get:
      consumes:
      - application/json
      description: Get server health status
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            additionalProperties: true
            type: object
      summary: Health check
      tags:
      - health
securityDefinitions:
  ApiKeyAuth:
    in: header
    name: Authorization
    type: apiKey
swagger: "2.0"
